"""gate new signups behind admin approval

Revision ID: 09b4dae9ba23
Revises: de9d902d681a
Create Date: 2026-08-03 22:45:21.042807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b4dae9ba23'
down_revision: Union[str, Sequence[str], None] = 'de9d902d681a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the approval gate without locking out anyone who already has access.

    The column defaults to 0 so that future signups are unapproved, but every
    account that exists at this point predates the gate and was already able to
    sign in. Backfilling them to approved is what stops this migration locking
    the administrator out of their own platform.
    """
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False))

    op.execute("UPDATE users SET is_approved = 1")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
