"""baseline schema

Revision ID: 44a67695df92
Revises: 
Create Date: 2026-07-25 07:24:49.832139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a67695df92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_logs_id'), ['id'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=30), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_id'), ['id'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_key', sa.String(length=100), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username_key'), ['username_key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('automation_active', sa.Boolean(), nullable=True),
    sa.Column('cost_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('plan_slug', sa.String(length=50), nullable=False),
    sa.Column('automation_mode', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cookie_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proxy_host', sa.String(length=255), nullable=True),
    sa.Column('proxy_port', sa.Integer(), nullable=True),
    sa.Column('proxy_username', sa.String(length=100), nullable=True),
    sa.Column('proxy_password', sa.String(length=100), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('automation_runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('runner_type', sa.String(length=30), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('automation_runners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_runners_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_id'), ['id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_id'), ['id'], unique=False)

    op.create_table('meta_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('connected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('instagram_user_id', sa.String(length=100), nullable=False),
    sa.Column('instagram_username', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_user_id', name='uq_meta_connection_instagram_user'),
    sa.UniqueConstraint('workspace_id', name='uq_meta_connection_workspace')
    )
    with op.batch_alter_table('meta_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_connections_instagram_user_id'), ['instagram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_connections_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_connections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('opt_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opt_outs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opt_outs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opt_outs_username'), ['username'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_setting_workspace_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('plan_slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('tg_bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=False),
    sa.Column('bot_token_hash', sa.String(length=128), nullable=True),
    sa.Column('bot_username', sa.String(length=100), nullable=True),
    sa.Column('bot_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_bot_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_bot_configs_bot_token_hash'), ['bot_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_bot_configs_id'), ['id'], unique=False)

    op.create_table('tg_message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_message_templates_id'), ['id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_id'), ['id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consent_source', sa.String(length=60), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('trigger_keyword', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)

    op.create_table('monitored_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('trigger_keyword', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_posts_id'), ['id'], unique=False)

    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('message_sent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_username'), ['username'], unique=False)

    op.create_table('tg_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['tg_bot_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_channels_id'), ['id'], unique=False)

    op.create_table('processed_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['monitored_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_comments_username'), ['username'], unique=False)

    op.create_table('tg_moderation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_moderation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_moderation_rules_id'), ['id'], unique=False)

    op.create_table('tg_post_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('content_preview', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_post_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_post_logs_id'), ['id'], unique=False)

    op.create_table('tg_scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=50), nullable=True),
    sa.Column('batch_messages', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_scheduled_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_scheduled_posts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_scheduled_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_scheduled_posts_id'))

    op.drop_table('tg_scheduled_posts')
    with op.batch_alter_table('tg_post_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_post_logs_id'))

    op.drop_table('tg_post_logs')
    with op.batch_alter_table('tg_moderation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_moderation_rules_id'))

    op.drop_table('tg_moderation_rules')
    with op.batch_alter_table('processed_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_comments_username'))
        batch_op.drop_index(batch_op.f('ix_processed_comments_id'))

    op.drop_table('processed_comments')
    with op.batch_alter_table('tg_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_channels_id'))

    op.drop_table('tg_channels')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_username'))
        batch_op.drop_index(batch_op.f('ix_targets_id'))

    op.drop_table('targets')
    with op.batch_alter_table('monitored_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_posts_id'))

    op.drop_table('monitored_posts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('tg_message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_message_templates_id'))

    op.drop_table('tg_message_templates')
    with op.batch_alter_table('tg_bot_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_bot_configs_id'))
        batch_op.drop_index(batch_op.f('ix_tg_bot_configs_bot_token_hash'))

    op.drop_table('tg_bot_configs')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('opt_outs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opt_outs_username'))
        batch_op.drop_index(batch_op.f('ix_opt_outs_id'))

    op.drop_table('opt_outs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('meta_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_connections_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_meta_connections_token_hash'))
        batch_op.drop_index(batch_op.f('ix_meta_connections_instagram_user_id'))
        batch_op.drop_index(batch_op.f('ix_meta_connections_id'))

    op.drop_table('meta_connections')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_id'))

    op.drop_table('message_templates')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_id'))

    op.drop_table('media_files')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('automation_runners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_runners_id'))

    op.drop_table('automation_runners')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))
        batch_op.drop_index(batch_op.f('ix_workspaces_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username_key'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_id'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_logs_id'))

    op.drop_table('bot_logs')
    # ### end Alembic commands ###
