"""add match_mode to monitored posts

Revision ID: de9d902d681a
Revises: 3a9fabb7d6cf
Create Date: 2026-08-03 21:56:57.308242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9d902d681a'
down_revision: Union[str, Sequence[str], None] = '3a9fabb7d6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_mode', sa.String(length=20), server_default='exact', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_posts', schema=None) as batch_op:
        batch_op.drop_column('match_mode')

    # ### end Alembic commands ###
